name: release
on:
  create:
    tags:
      - v*
  push:
    branches:
      - main

# Note the only differences between release and canary-release jobs are:
# - only canary passes --overwrite flag
# - the VERSION make variable passed to 'make dist checksum' is expected to
#   be "canary" if the job is triggered by a push to "main" branch. If the
#   job is triggered by a tag push, VERSION should be the tag ref.
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # pin@5.0.0
        with:
          go-version: '1.21'

      - name: Run unit tests
        run: make test-coverage

      - name: Build Helm Binaries
        run: |
          set -eu -o pipefail

          make build-cross
          make dist checksum VERSION="${{ github.ref_name }}"
      - name: Release on Github
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _dist/*
